# Generated by Django 2.0.3 on 2018-11-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('s_name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
                ('s_json', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '接口结构',
                'db_table': 'TestSchema',
            },
        ),
    ]
