# Generated by Django 2.0.3 on 2018-11-01 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0002_testschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='testschema',
            name='belong_project',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ProjectInfo', verbose_name='所属项目'),
            preserve_default=False,
        ),
    ]
